name: test

on: push

jobs:
  test-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Bissect
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          options: --volume ${{ github.workspace }}:/work --workdir /work --privileged
          run: |
            #pacman --noconfirm -Syu git curl
            
            pacman --noconfirm -Syu git
            
            pacman -Sy --noconfirm \
              bash \
              sudo \
              openssl \
              python3 \
              python-pip \
              icu \
              base-devel \
              libxml2 \
              glibc \
              openbsd-netcat \
              squid \
              jq
              # Temporary install to patch a python3/pip crash
              pacman -Sy --noconfirm expat
  
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            export PATH=$HOME/.cargo/bin:$PATH
            ./run.sh
