name: test

on:
  push:
  workflow_dispatch:

jobs:
  test-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run libcurl HTTP3
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          options: --volume ${{ github.workspace }}:/work --workdir /work --privileged
          run: |
            echo "::group::Installation prerequisites"
            pacman -Syu --noconfirm curl pkgconf gcc
            echo "::engroup::"

            echo "::group::Build"
            ./build.sh
            echo "::engroup::"

            echo "::group::Run"
            ./libcurl.sh 20 1
            echo "::engroup::"
