name: test

on: push

jobs:
  test-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run curl HTTP3
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          options: --volume ${{ github.workspace }}:/work --workdir /work --privileged
          run: |
            curl --version
            ./run.sh https://google.com 100 1
