name: test

on:
  push:
  workflow_dispatch:

jobs:
  test-hurl-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run hurl HTTP3
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux
          options: --volume ${{ github.workspace }}:/work --workdir /work --privileged
          run: |
            echo "::group::Installation Hurl prerequisites"
            ./setup_build_hurl.sh
            echo "::engroup::"

            echo "::group::Build"
            ./build_hurl.sh
            echo "::engroup::"

            echo "::group::Run"
            ./run_hurk-5.0.0.sh 20 1
            echo "::engroup::"
